apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: register-app
  name: register-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: register-app
    spec:
      containers:
      - image: kamrandevops23/register-app-pipeline:latest
        name: register-app-pipeline
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: register-app
  name: app-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: register-app
  type: LoadBalancer
